#VBTC
vbtc.exchange
Page Title: VBTC - Buy and sell Bitcoin in Vietnam
author: THONG NGO
email: quangthong1011@gmail.com
description: Bitcoin, Password, User (computing),Server (computing), Deposit account
             Multisignature, Open-source software, Transparency (behavior), Solvency
             Surity hacker, Blockchain, Cryptocurrency wallet, Algorithmic trading
             Trade, Wallet, Market maker, Broker, Payment processor, .NET Framework,
baseurl: "https://vbtc.exchange"
url: "https://vbtc.github.io"
show_excerpts

twitter_username: vbtc_vietnam
facebook_username: VBTC.vn 
github_username: vbtc
rss: feed.xml

google_analytics: UA-134715319-1

permalink: /:year/:categories/:title
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
